### ISSUE TITLE
String parameters turn to numbers

### ISSUE THREAD

**Issue by selb** [akojo/clutch#3]
The current version published on LuaRocks seems to coerce number-like string parameters to numbers. The good news is that the latest code in this repo resolves the issue, at least for me. :) Type affinity issues with DBs only opened by clutch were noted in #2, and this is the situation in which I triggered this issue as well.

Minimal script to reproduce the issue:

```lua
local clutch = require('clutch')
local db = clutch.open(':memory:')

local s = '123456'
db:update('CREATE TABLE tab (fld TEXT)')
db:update("INSERT INTO tab VALUES (?)", { s }) -- Inserts '123456.0'
-- db:update("INSERT INTO tab VALUES ('123456')") -- Works as expected.
print(db:queryone('SELECT * FROM tab').fld)
```

Expected output:

```
123456
```

Actual output:

```
123456.0
```

(Thanks for this library, by the way. It is very clean and usable, whereas every other way I found of SQLiteing in Lua was pretty miserable.)

**Comment by akojo** [comment]
Interesting. I pushed a new release (1.3.2) to LuaRocks, it seems to work as expected when I tested installing clutch from there. Try out the latest version if it now indeed fixes the issue.

**Comment by selb** [comment]
Confirmed fixed for me on the latest version from LuaRocks. Tested by `luarocks remove` then `luarocks install ...` to make sure my own build wasn't in the way.

I forgot to post my versions of Lua and SQLite originally. Here they are just in case:

```
$ sqlite3 --version
3.37.2 2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5dalt1
$ lua -v
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
```
